name: 'deploy snowflake tasks'

on:
  push:
    paths:
      - 'snowflake/infra/tasks/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-tasks:
    runs-on: ubuntu-latest
    container: infinityworks/awscli-terraform-snowflake:1.1.0
    permissions:
      id-token: write
      contents: read
    env:
      ENV: dev
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLENAME: SYSADMIN

    steps:
    - name: checkout-code
      uses: actions/checkout@v2

    - name: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/snow-cannon-ci-deployment-role-dev
        role-session-name: CI-deployment
        aws-region: ${{ secrets.AWS_REGION }}
        role-duration-seconds: 900


    - name: deploy-tasks
      run: |
        cd snowflake/infra/tasks
        terraform init
        terraform workspace new $ENV || terraform workspace select $ENV
        terraform plan
        terraform apply -input=false -auto-approve
