name: 'integration tests'

on:
  push:
    paths:
      - 'project_setup.py'
      - 'tests/**'
      - './.github/workflows/integration-tests.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/infinityworks/awscli-terraform-snowflake:1.1.0
    env:
      ENV: dev

    steps:
    - name: checkout-code
      uses: actions/checkout@v2

    - name: cache-python-requirements
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: install-python-requirements
      run: |
        pip3 install --requirement requirements.txt

    - name: run-project-setup-tests
      run: |
        pytest tests -vvv
